---
name: "pipeline-components-haskell-hlint"
description: "haskell-hlint by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory or files to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: "-j"
runs:
  using: "docker"
  image: docker://pipelinecomponents/haskell-hlint
  args:
    - hlint
    - "${{ inputs.options }}"
    - "${{ inputs.directory }}"
